name: 'Psalm baseline progress'
description: 'Calculates psalm baseline diff'
branding: 
  icon: file-minus
  color: purple
inputs:
  base_ref:
    description: 'git ref to use for calculating the base_score'
    required: false
    default: '${{ github.event.pull_request.base.sha }}'
  head_ref:
    description: 'git ref to use for calculating the head_score'
    required: false
    default: 'HEAD'
  path_to_baseline:
    description: 'Path to the baseline file'
    required: false
    default: './psalm-baseline.xml'
outputs:
  base_score:
    description: 'Baseline score for the pull request base'
  head_score:
    description: 'Baseline score for the pull request head'
  score_diff:
    description: 'Difference between the two scores (head_score - base_score)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BASE_REF: ${{ inputs.base_ref }}
    HEAD_REF: ${{ inputs.head_ref }}
    PATH_TO_BASELINE: ${{ inputs.path_to_baseline }}
