on:
  pull_request:
jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: psalm-baseline-progress-action
        id: psalm-baseline-progress-action
        uses: ./
      - name: Comment on PR
        if: steps.psalm-baseline-progress-action.outputs.score_diff != 0
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            psalm baseline score changed: **${{ steps.psalm-baseline-progress-action.outputs.base_score }}** -> **${{ steps.psalm-baseline-progress-action.outputs.head_score }}**
          comment_tag: 'psalm_baseline_score_comment'
